## 习题解析

### 1.异常处理

- 在实际应用中，当一个异常出现时，单靠某个方法无法完全处理该异常，必须由几个方法协作才可以处理，这个时候同时使用catch和throw语句。
- **捕获异常后，只对异常进行部分处理，还有些处理需要在该方法的调用者中才能完成**，所以应该再次抛出异常，让该方法的调用者也能捕获到异常。
- 程序运行时异常由Java虚拟机自动进行处理。
- 先执行try，不管有没有执行catch都会执行finally。如果try中有return，则先执行finally再执行return。

### 2.异常体系

```java
/**
* 1.错误：不需要捕捉，属于系统性错误。
* 2.检查异常/编译期异常：必须被 try{}catch语句块所捕获,或者在方法签名里通过throws子句声明。Java编译器要进行
*   检查，虚拟机运行时也要检查。
* 3.运行时异常：个人判断是否捕获和处理，虚拟机运行时会检查。
*
*/

Throwable   
|-- Error（错误）   
|-- Exception
    |-- IOException（检查异常/编译期异常）
            |-- EOFException
            |-- FileNotFoundException
            |-- MalformedURLException
            |-- UnknownHostException
    |-- ClassNotFoundException（检查异常/编译期异常）
    |-- CloneNotSupportedException（检查异常/编译期异常）
    |-- RuntimeException（运行时异常）
        |-- ArithmeticException
        |-- ClassCastException
        |-- IllegalArgumentException
        |-- IllegalStateException
        |-- IndexOutOfBoundsException
        |-- NoSuchElementException
        |-- NullPointerException

```

### 3.异常关键字

- throws用在方法上，声明该方法不需要处理的异常类型，用在方法上后面跟异常类名，可以是多个异常类。
- throw用于抛出具体异常类的对象，用在方法内后面跟异常对象只能是一个异常类型实体。
- throws关键字可以在方法上声明该方法要抛出的异常，然后在方法内部通过throw抛出异常对象。
- try块必须和catch块或和finally同在，不能单独存在，二者必须出现一个。
- finally块总会执行，不论是否有错误出现。但是若try语句块或会执行的catch语句块使用了JVM系统退出语句，finally块就不会被执行了。一般我们把关闭资源的代码放在finally里面保证资源总是能关闭。如果在try或者catch中使用了return，会先执行finally再执行return。

### 4.finally块不会执行的情况

- finally块中发生了异常。
- 程序所在线程死亡。
- 在前面的代码中用了System.exit()。
- 关闭了CPU。

### 5.异常catch注意点

- 在异常处理中，若try中的代码可能产生多种异常则可以对应多个catch语句，若catch中的参数类型有父类子类关系，此时应该将父类放在后面，子类放在前面。